"""Drafts the progress note — Gemini when a key is configured, mock otherwise."""

import asyncio
import logging

from .config import get_settings
from .schemas import ReviewItem

logger = logging.getLogger("therapist_copilot")

SYSTEM_INSTRUCTION = """You are a documentation assistant for a physiotherapist reviewing \
RehabTrace path-tracing sessions. Draft a short factual progress note (under 130 words) \
from the structured session data provided.

Structure: one line of session context, then short observations grouped as \
"Data quality", "Task performance", and "Compared with participant's recent sessions".

Rules:
- Describe task performance only. Never interpret measurements as neurological \
recovery, deterioration, or treatment response.
- Never diagnose or recommend treatment changes.
- Refer to the participant only by the anonymous ID given.
- If data quality was flagged, lead with that.
- Neutral clinical register; no encouragement, no advice to the participant.
- End with: "Draft generated by RehabTrace Copilot — pending therapist review."
"""


def _note_context(item: ReviewItem, run: dict) -> str:
    scores = run.get("scores") or {}
    metrics = run.get("metrics") or {}
    timing = run.get("timing") or {}

    lines = [
        f"Participant: {item.participant_id}",
        f"Session received: {item.received_at or 'unknown'}",
        f"Data quality verdict: {item.quality_verdict}"
        + (f" ({'; '.join(item.quality_reasons)})" if item.quality_reasons else ""),
        f"Accuracy score (0-100): {scores.get('accuracy')}",
        f"Stability score (0-100): {scores.get('stability')}",
        f"Coverage: {metrics.get('coverage_pct')} %",
        f"Tremor RMS: {metrics.get('tremor_rms_deg_s')} deg/s",
        f"Duration: {(timing.get('duration_ms') or 0) / 1000:.1f} s",
    ]
    if item.sessions_compared:
        lines.append(
            f"Compared with the participant's last {item.sessions_compared} sessions:"
        )
        for d in item.deltas:
            lines.append(
                f"- {d.label}: {d.current} (their average {d.participant_avg}, "
                f"change {d.delta:+})"
            )
    else:
        lines.append("No previous sessions — baseline session.")
    return "\n".join(lines)


async def draft_note(item: ReviewItem, run: dict) -> tuple[str, bool]:
    """Returns (note_text, is_mock)."""
    settings = get_settings()
    if settings.mock_mode:
        return _mock_note(item, run), True

    from google import genai
    from google.genai import types

    client = genai.Client(api_key=settings.gemini_api_key)
    try:
        response = await asyncio.wait_for(
            client.aio.models.generate_content(
                model=settings.gemini_model,
                contents=_note_context(item, run),
                config=types.GenerateContentConfig(
                    system_instruction=SYSTEM_INSTRUCTION,
                    max_output_tokens=settings.max_output_tokens,
                    temperature=0.2,
                    # gemini-2.5-flash is a thinking model; without this it can
                    # spend the whole token budget on hidden reasoning and return
                    # empty text (finish_reason=MAX_TOKENS), forcing a mock
                    # fallback. These notes are short and structured — no thinking.
                    thinking_config=types.ThinkingConfig(thinking_budget=0),
                ),
            ),
            timeout=settings.gemini_timeout_s,
        )
        text = (response.text or "").strip()
        if text:
            return text, False
        logger.warning("Gemini returned an empty note; falling back to mock")
    except asyncio.TimeoutError:
        logger.warning("Gemini note drafting timed out; falling back to mock")
    except Exception:
        logger.exception("Gemini note drafting failed; falling back to mock")
    # A failed LLM call must never block triage — fall back to the template.
    return _mock_note(item, run), True


def _mock_note(item: ReviewItem, run: dict) -> str:
    scores = run.get("scores") or {}
    metrics = run.get("metrics") or {}
    parts = [f"Session note — participant {item.participant_id}."]

    if item.quality_verdict == "unusable":
        parts.append(
            "Data quality: session flagged as unusable. "
            + " ".join(item.quality_reasons)
            + " Suggest repeating the session before drawing on these measurements."
        )
    elif item.quality_verdict == "usable_with_warnings":
        parts.append("Data quality: usable with caveats. " + " ".join(item.quality_reasons))
    else:
        parts.append("Data quality: calibration valid, sensor data complete.")

    perf = []
    if scores.get("accuracy") is not None:
        perf.append(f"accuracy {scores['accuracy']}")
    if scores.get("stability") is not None:
        perf.append(f"stability {scores['stability']}")
    if metrics.get("coverage_pct") is not None:
        perf.append(f"coverage {metrics['coverage_pct']}%")
    if perf:
        parts.append("Task performance: " + ", ".join(perf) + ".")

    if item.sessions_compared and item.deltas:
        changes = ", ".join(
            f"{d.label} {d.delta:+} vs. recent average {d.participant_avg}"
            for d in item.deltas
        )
        parts.append(
            f"Compared with the last {item.sessions_compared} sessions: {changes}."
        )
    else:
        parts.append("Baseline session — no prior sessions for comparison.")

    parts.append("Draft generated by RehabTrace Copilot — pending therapist review.")
    return "\n".join(parts)
